services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ${PWD}/docker/postgres_bootstrap.sql:/docker-entrypoint-initdb.d/z99_dump.sql
    networks:
      - test_network

  common_modules_test_runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: jyablonski_common_modules
    environment:
      - ENV_TYPE=docker_dev
    depends_on:
      - postgres
    networks:
      - test_network
    links:
      - postgres:postgres
    volumes:
      - ${PWD}/pyproject.toml/:/home/appuser/pyproject.toml
      - ${PWD}/src/:/home/appuser/src
      - ${PWD}/tests/:/home/appuser/tests
    command: python3 -m pytest -vv --cov-report term --cov-report xml:coverage.xml --cov=src --color=yes

networks:
  test_network: