name: Common Modules Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UV_VERSION: "0.7.13"

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          make test

  cd_pipeline:
    runs-on: ubuntu-latest
    needs: ci_pipeline
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && success()
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: uv Build
        run: uv build --no-cache

      - name: uv Publish
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}

  deploy-alert:
    needs: cd_pipeline
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Slack Deploy Notification
        uses: jyablonski/actions/slack_alert@v1
        with:
          message: ${{ job.status == 'success' && 'Common Modules Deployed to Production' || 'Common Modules Failed to deploy properly' }}
          title: ${{ job.status == 'success' && 'Common Modules Deploy Pipeline' || 'Common Modules Deploy Failure' }}
          color: ${{ job.status == 'success' && 'good' || 'danger' }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
