name: Common Modules Test Pipeline
on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          make test

      # tried doing this in the same container but it's a pain
      # should just install poetry and run coveralls that way
      # - name: Run Coveralls in Docker
      #   run: |
      #     docker compose -f docker/docker-compose-test.yml exec common_modules_test_runner poetry run coveralls
